### ISSUE TITLE
Entrée "Thaïlande" instable dans le champ "pays" lors d'une première édition

### ISSUE THREAD

**Issue by BTHOM** [GrottoCenter/GrottoCenter#53]
Quand on édite pour la première fois une cavité de Thaïlande (précédemment déversée en nombre ?), le champ "pays" se remet à blanc et il faut à nouveau choisir le pays grâce au matchcode.

Ce bug ne se manifeste plus lors des éditions ultérieures de la même  cavité.

**Comment by bsoufflet** [comment]
Je viens de corriger le problème. Il y avait des espaces devant le code pays "TH" en base de données.
J'ai exécuté la query suivante : 
UPDATE
    T_entry
SET
    Country = LTRIM(RTRIM(Country));
