### ISSUE TITLE
La longueur des champs "Commune"  et "Etat Région ou Département" est insuffisante

### ISSUE THREAD

**Issue by BTHOM** [GrottoCenter/GrottoCenter#56]
La fusion administrative de communes ainsi que celle des régions entraînent des allongements de noms.
Ces nouveaux noms n'entrent plus dans l'espace octroyé à ces champs.
Par exemple, les noms de commune suivants se retrouvent tronqués : 
- La Vacquerie-et-Saint-Martin-de-Castries
- Rouffignac-Saint-Cernin-de-Reilhac
- Saint-Félix-de-Reillac-et-Mortemart
- ...

**Comment by urien** [comment]
Cela représente 40 caractères pour le plus long. Il faudrait essayer de permettre 50 caractères

**Comment by BTHOM** [comment]
J'espère que prolonger les champs, voire ajouter de nouveaux champs (localité, région, ) est une opération facile sous la V2 et ultérieurement sous la V3.

Sinon, la base de données souffrira éternellement d'une tare majeure : la rigidité

**Comment by urien** [comment]
C'est paramétré dans la base de données à 32 caractères. Il faut attendre le retour de Benjamin. Je vais regarder s'il y a des limitations qui ont aussi été placées dans le code. Je crois qu'il faut aussi augmenter la taille des champs "massif" et "réseau" qui sont de la même taille

**Comment by bsoufflet** [comment]
C"est corrigé! 64 caractères maintenant!
